# Generated by Django 4.2.25 on 2025-11-09 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "match_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "applications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AudioInterviewAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audio_file_path", models.CharField(max_length=500)),
                ("transcribed_text", models.TextField(blank=True, null=True)),
                ("audio_duration", models.FloatField(blank=True, null=True)),
                ("transcription_confidence", models.FloatField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "audio_interview_answers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AudioInterviewEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overall_score", models.IntegerField()),
                ("strengths", models.JSONField(blank=True, null=True)),
                ("weaknesses", models.JSONField(blank=True, null=True)),
                ("correct_answer", models.TextField(blank=True, null=True)),
                ("answer_analysis", models.TextField(blank=True, null=True)),
                ("improvement_tips", models.JSONField(blank=True, null=True)),
                ("follow_up_questions", models.JSONField(blank=True, null=True)),
                (
                    "audio_feedback_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("evaluated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "audio_interview_evaluations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AudioInterviewQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("difficulty", models.CharField(blank=True, max_length=20, null=True)),
                ("tips", models.TextField(blank=True, null=True)),
                ("expected_answer_focus", models.TextField(blank=True, null=True)),
                (
                    "audio_file_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("audio_duration", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "audio_interview_questions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AudioInterviewSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_description", models.TextField()),
                ("difficulty", models.CharField(default="medium", max_length=20)),
                ("voice_id", models.CharField(blank=True, max_length=100, null=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "audio_interview_sessions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.TextField()),
                ("parsed_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "cvs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CVEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("embedding", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "cv_embeddings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_answer", models.TextField()),
                ("submitted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "interview_answers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overall_score", models.IntegerField()),
                ("strengths", models.JSONField(blank=True, null=True)),
                ("weaknesses", models.JSONField(blank=True, null=True)),
                ("correct_answer", models.TextField(blank=True, null=True)),
                ("answer_analysis", models.TextField(blank=True, null=True)),
                ("improvement_tips", models.JSONField(blank=True, null=True)),
                ("follow_up_questions", models.JSONField(blank=True, null=True)),
                ("evaluated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "interview_evaluations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("difficulty", models.CharField(max_length=20)),
                ("tips", models.TextField(blank=True, null=True)),
                ("expected_answer_focus", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "interview_questions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InterviewSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_description", models.TextField()),
                ("difficulty", models.CharField(default="medium", max_length=20)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "interview_sessions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("requirements", models.TextField(blank=True, null=True)),
                ("responsibilities", models.TextField(blank=True, null=True)),
                ("employment_type", models.TextField(blank=True, null=True)),
                ("salary_range", models.TextField(blank=True, null=True)),
                ("posted_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField()),
                ("posted_by", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "jobs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JobEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("embedding", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "job_embeddings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section", models.TextField()),
                ("recommendation_text", models.TextField()),
                ("suggested_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "recommendations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SbCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("website", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "companies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SbUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.TextField()),
                ("full_name", models.TextField()),
                ("email", models.TextField()),
                ("password_hash", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "skills",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("viewed", "Viewed"),
                            ("screening", "Screening"),
                            ("interview", "Interview"),
                            ("interviewing", "Interviewing"),
                            ("offer", "Offer"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("accepted", "Accepted"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        db_column="application_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="statuses",
                        to="api.application",
                    ),
                ),
            ],
            options={
                "db_table": "application_statuses",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.CreateModel(
            name="ApplicationNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        db_column="application_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="notes",
                        to="api.application",
                    ),
                ),
            ],
            options={
                "db_table": "application_notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
