# Generated by Django 4.2.25 on 2025-11-09 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_application_audiointerviewanswer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_description", models.TextField(blank=True, null=True)),
                ("cover_letter_text", models.TextField()),
                ("version_name", models.CharField(default="Version 1", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cv",
                    models.ForeignKey(
                        db_column="cv_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cover_letters",
                        to="api.cv",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        db_column="job_id",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cover_letters",
                        to="api.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cover_letters",
                        to="api.sbuser",
                    ),
                ),
            ],
            options={
                "db_table": "cover_letters",
                "ordering": ["-created_at"],
            },
        ),
    ]
