# Generated by Django 4.2.25 on 2025-11-09 12:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_coverletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationCoverLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        db_column="application_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cover_letter_links",
                        to="api.application",
                    ),
                ),
                (
                    "cover_letter",
                    models.ForeignKey(
                        db_column="cover_letter_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="application_links",
                        to="api.coverletter",
                    ),
                ),
            ],
            options={
                "db_table": "application_cover_letters",
                "ordering": ["-created_at"],
                "unique_together": {("application", "cover_letter")},
            },
        ),
    ]
