# Generated by Django 4.2.25 on 2025-12-14 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_resume_workexperience_resumeskill_resumeproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Mock Interview', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('feedback_summary', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisualAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_ms', models.IntegerField()),
                ('smile_score', models.FloatField(default=0.0)),
                ('eye_contact_score', models.FloatField(default=0.0)),
                ('posture_score', models.FloatField(default=0.0)),
                ('nervousness_score', models.FloatField(default=0.0)),
                ('dominant_expression', models.CharField(blank=True, max_length=50)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_analyses', to='api.videointerview')),
            ],
            options={
                'ordering': ['timestamp_ms'],
            },
        ),
    ]
