# Generated by Django 4.2.25 on 2025-12-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_videointerview_visualanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='videointerview',
            name='interview_type',
            field=models.CharField(choices=[('HR', 'HR'), ('Technical', 'Technical')], default='HR', max_length=20),
        ),
        migrations.AddField(
            model_name='videointerview',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='videointerview',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
