# Generated by Django 4.2.25 on 2025-12-26 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_videointerview_interview_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodingProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("leetcode", "LeetCode"),
                            ("hackerrank", "HackerRank"),
                        ],
                        max_length=20,
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("analysis", models.JSONField(blank=True, default=dict)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["platform"],
                "unique_together": {("user", "platform")},
            },
        ),
    ]
