# Generated by Django 4.2.25 on 2025-12-27 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_add_coding_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeetCodeAnalysisHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee_identifier",
                    models.CharField(help_text="Username or CSV name", max_length=255),
                ),
                (
                    "leetcode_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("leetcode_url", models.URLField()),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                ("total_solved", models.IntegerField(default=0)),
                ("easy_solved", models.IntegerField(default=0)),
                ("medium_solved", models.IntegerField(default=0)),
                ("hard_solved", models.IntegerField(default=0)),
                (
                    "problem_solving_score",
                    models.IntegerField(default=0, help_text="Score out of 100"),
                ),
                ("ranking", models.IntegerField(default=0)),
                ("acceptance_rate", models.FloatField(default=0.0)),
                ("current_streak", models.IntegerField(default=0)),
                ("max_streak", models.IntegerField(default=0)),
                (
                    "activity_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "full_stats",
                    models.JSONField(
                        default=dict, help_text="Complete stats from LeetCode API"
                    ),
                ),
                (
                    "analysis_data",
                    models.JSONField(default=dict, help_text="AI analysis results"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leetcode_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LeetCode Analysis Histories",
                "ordering": ["-analyzed_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "employee_identifier", "-analyzed_at"],
                        name="api_leetcod_company_f6e9ff_idx",
                    ),
                    models.Index(
                        fields=["company", "-analyzed_at"],
                        name="api_leetcod_company_40a6b9_idx",
                    ),
                ],
            },
        ),
    ]
