# Generated by Django 4.2.25 on 2025-12-27 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_leetcodeanalysishistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Employee name or identifier", max_length=255
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Internal employee ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("leetcode_username", models.CharField(max_length=100)),
                ("leetcode_url", models.URLField()),
                (
                    "team",
                    models.CharField(
                        blank=True,
                        help_text="Team or department name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Job role/title",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "auto_sync_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable automatic periodic syncing"
                    ),
                ),
                (
                    "sync_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        help_text="How often to automatically sync this employee's profile",
                        max_length=20,
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                (
                    "next_sync",
                    models.DateTimeField(
                        blank=True, help_text="Next scheduled sync time", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the employee",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this employee is currently being tracked",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("total_solved", "Total Problems Solved"),
                            ("easy_solved", "Easy Problems Solved"),
                            ("medium_solved", "Medium Problems Solved"),
                            ("hard_solved", "Hard Problems Solved"),
                            ("problem_solving_score", "Problem Solving Score"),
                            ("acceptance_rate", "Acceptance Rate"),
                            ("current_streak", "Current Streak"),
                            ("ranking", "Ranking (lower is better)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_value",
                    models.FloatField(help_text="Target value to achieve"),
                ),
                (
                    "current_value",
                    models.FloatField(
                        default=0, help_text="Current value (updated on sync)"
                    ),
                ),
                (
                    "start_value",
                    models.FloatField(default=0, help_text="Value when goal was set"),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                (
                    "target_date",
                    models.DateTimeField(help_text="Deadline for achieving the goal"),
                ),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="api.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-target_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "is_active"],
                        name="api_employe_employe_9f3661_idx",
                    ),
                    models.Index(
                        fields=["company", "is_active", "-target_date"],
                        name="api_employe_company_92a984_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["company", "is_active"], name="api_employe_company_107ac1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["company", "team"], name="api_employe_company_a2e8d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["company", "-last_synced"],
                name="api_employe_company_b01927_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("company", "leetcode_username")},
        ),
    ]
